# Generated by Django 4.1.3 on 2024-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=100)),
                ("auther", models.CharField(max_length=100)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
